### PR TITLE
Abstracted out formats in src/config.py

### PR DESCRIPTION
**Pull request by psachin**
Cleanups:
- Renamed classifier/ to src/
- Relevant changes to setup.py

### CODE REVIEW

**Comment by psachin** [comment]
The title is misleading. The file path is src/config.py

**Comment by bhrigu123** [comment]
The config.py file looks good,
but why have you put the main method in `__init__.py` ? I think that should remain in the classifier.py file, and __init__.py kept empty. 
As far as I've seen, init.py is used for package importing purposes only, and contains **import** statements only.

**Comment by psachin** [comment]
There are few reasons:

1. __init__.py should hold the main()..the starting point of the program
according to standards. In this way the 'entry_points' in setup.py file
points to 'classifier:main' and not 'classifier.classifier:main' which is
cleaner.
2. main() holds argparser..which is not actual code but arguments handler.
And this should be abstracted out from real code at some point of time. I
think this is a right time.
3. It is not necessary that __init__.py should be empty or only do imports,
but it should do 'initialization/loading' work. Please see source code on
'pip', they have much complex __init__.py
4. I personally think we are moving toward more standard approach suggested
by Python documentation.

On Thu, Jan 28, 2016 at 7:12 PM, Bhrigu Srivastava <notifications@github.com
> wrote:

> The config.py file looks good,
> but why have you put the main method in __init__.py ? I think that should
> remain in the classifier.py file, and *init*.py kept empty.
> As far as I've seen, init.py is used for package importing purposes only,
> and contains *import* statements only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhrigu123/classifier/pull/30#issuecomment-176189673>.
>



-- 
Sachin

**Comment by psachin** [comment]
@bhrigu123 seems like you are not convinced ?

**Comment by yask123** [comment]
@psachin I won't recommend moving main function to `__init__.py` file. 
It should only be used for initialisation purposes. (or can contain just import statements).

**Comment by psachin** [comment]
no problem

On Fri, Jan 29, 2016 at 11:16 PM, Yask Srivastava <notifications@github.com>
wrote:

> @psachin <https://github.com/psachin> I won't recommend moving main
> function to __init__.py file.
> It should only be used for initialisation purposes. (or can contain just
> import statements).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhrigu123/classifier/pull/30#issuecomment-176882616>.
>



-- 
Sachin

**Pull request closed without merging**
