### PR TITLE
Fix #43: os path join raise unicode decode error

### LINKED ISSUE #43: UnicodeDecodeError raised when the name of candidate (file or directory) is Chinese
I get the `UnicodeDecodeError` when run **classifier** in directory including Chinese filenames.

```
Traceback (most recent call last):
  File ".../bin/classifier", line 11, in <module>
    sys.exit(main())
  File ".../lib/python2.7/site-packages/classifier/classifier.py", line 104, in main
    classify_by_date('DD-MM-YYYY', args.output)
  File ".../lib/python2.7/site-packages/classifier/classifier.py", line 58, in classify_by_date
    moveto(file, directory, folder)
  File ".../lib/python2.7/site-packages/classifier/classifier.py", line 20, in moveto
    to_file = os.path.join(to_folder, file)
  File ".../lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by yittg**
Fix #43

### CODE REVIEW

**Comment by bhrigu123** [comment]
Can you give some test cases for me to test ?

**Comment by yittg** [comment]
@bhrigu123 I have added a unittest case in the patch, please review it, thanks.

**Comment by yittg** [comment]
However, it seems only work and need to do decode in Python2.
In Python3, this patch will raise another Error because of `'str' object has no attribute 'decode'`.

**Comment by yittg** [comment]
@bhrigu123 I modified the patch to be compatible with both Python2 and Python3.

**Comment by bhrigu123** [comment]
@yittg are you sure that it is compatible for python3 also? 
because In my Ubuntu machine python3 gives import error:
`ImportError: cannot import name 'getcwd'`

(I had forgotten to check for python3 before merging)

**Comment by yittg** [comment]
Oh, I'm very sorry for that I didn't noticed that moves for `getcwd` is supported just in `six >= 1.10.0`.
So actually it is compatible for py2 and py3, let me update the require for `six >= 1.10.0`.

**Pull request merged**
